name: Tests ORION

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  unit-tests:
    name: Tests Unitaires
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Installer les dépendances
        run: npm ci
      
      - name: Exécuter les tests unitaires
        run: npm run test -- --run
      
      - name: Générer le rapport de couverture
        run: npm run test:coverage -- --run
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage/coverage-final.json
          flags: unittests
          name: codecov-orion

  e2e-tests:
    name: Tests E2E Playwright
    runs-on: ubuntu-latest
    timeout-minutes: 60
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Installer les dépendances
        run: npm ci
      
      - name: Installer les navigateurs Playwright
        run: npx playwright install --with-deps
      
      - name: Exécuter les tests E2E
        run: npm run test:e2e
      
      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  lint:
    name: Vérification du code
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Installer les dépendances
        run: npm ci
      
      - name: Vérification ESLint
        run: npm run lint
      
      - name: Build
        run: npm run build
